#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 0
bspc config focused_border_color \#FF9D46

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
/home/mysteriousjim/.screenlayout/Default.sh &
polybar &
redshift &
